/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fHt3KzRiE4N
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
import Link from "next/link"
import { Textarea } from "@/components/ui/textarea"

export function MainPage() {
  return (
    <>
      <header className="flex h-16 w-full items-center justify-between px-4 md:px-6 bg-gradient-to-br from-[#fbbf24] to-[#ef4444]">
        <div className="flex items-center">
          <div className="mr-4">
            <CakeIcon className="h-10 w-10 text-white" />
          </div>
        </div>
        <div className="flex items-center gap-x-4 font-semibold">
          <Link className="text-white hover:underline ml-auto" href="#">
            About
          </Link>
          <Link className="text-white hover:underline" href="#">
            <GithubIcon className="h-6 w-6 text-white" />
          </Link>
        </div>
      </header>
      <div className="flex items-center justify-center min-h-screen p-4 text-center bg-gradient-to-br from-[#fbbf24] to-[#ef4444]">
        <div className="space-y-4">
          <h1 className="text-4xl font-extrabold tracking-tighter sm:text-6xl text-white">Happy Birthday!</h1>
          <p className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-white">
            Wishing you a fantastic day filled with the people and activities you love the most.
          </p>
          <Textarea
            className="w-full max-w-md p-3 border border-gray-200 border-gray-300 rounded-md focus:outline-none focus:ring focus:ring-blue-400 dark:border-gray-700 dark:focus:ring-gray-600 dark:bg-gray-800 text-gray-800 dark:text-gray-200 mx-auto bg-gradient-to-br from-[#fbbf24] to-[#ef4444/80] dark:border-gray-800"
            placeholder="Share your heartfelt birthday wish here"
          />
        </div>
      </div>
    </>
  )
}

function CakeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 21v-8a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8" />
      <path d="M4 16s.5-1 2-1 2.5 2 4 2 2.5-2 4-2 2.5 2 4 2 2-1 2-1" />
      <path d="M2 21h20" />
      <path d="M7 8v2" />
      <path d="M12 8v2" />
      <path d="M17 8v2" />
      <path d="M7 4h.01" />
      <path d="M12 4h.01" />
      <path d="M17 4h.01" />
    </svg>
  )
}


function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}
