/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VOe3Jtar0JX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
**/
export function SplashPage() {
  return (
    <div
      key="1"
      className="flex items-center justify-center min-h-screen p-4 text-center bg-gradient-to-br from-[#fbbf24] to-[#ef4444]"
    >
      <div className="space-y-4">
        <h1 className="text-4xl font-extrabold tracking-tighter sm:text-6xl text-white underline">
          It is April 30, 2024, a special day!
        </h1>
        <p className="text-lg text-white">Click anywhere to continue</p>
      </div>
    </div>
  )
}
